CREATE TABLE AUTHORITIES (AUTHORITY_ID BIGINT NOT NULL AUTO_INCREMENT, AUTHORITY VARCHAR(22), PRIMARY KEY (AUTHORITY_ID)) engine=InnoDB;

CREATE TABLE USERS (USER_ID BIGINT NOT NULL AUTO_INCREMENT, ENABLE BIT DEFAULT 0,
                    USERNAME varchar(33), FIRST_NAME varchar(33), LAST_NAME VARCHAR(33),  EMAIL VARCHAR(105) UNIQUE, PASSWORD VARCHAR(100),
                    PRIMARY KEY (USER_ID)) engine=InnoDB;

CREATE TABLE USERS_AUTHORITIES (USER_ID BIGINT NOT NULL, AUTHORITY_ID BIGINT NOT NULL,
                        PRIMARY KEY (USER_ID, AUTHORITY_ID)) engine=InnoDB;

CREATE TABLE UNITS (UNIT_ID BIGINT NOT NULL AUTO_INCREMENT,
                                  PRICE DOUBLE ,
                                  DESCRIPTION VARCHAR (500),
                                  REGION VARCHAR (55),
                                  TITLE VARCHAR (55),
                                  PRIMARY KEY (UNIT_ID)) engine=InnoDB;


CREATE TABLE REVIEWS(REVIEW_ID BIGINT NOT NULL AUTO_INCREMENT,
                                      RATE SMALLINT,
                                      COMMENT VARCHAR (500),
                                      USER_ID BIGINT NOT NULL,
                                      UNIT_ID BIGINT NOT NULL,
                        PRIMARY KEY (REVIEW_ID)) engine=InnoDB;

ALTER TABLE USERS_AUTHORITIES ADD CONSTRAINT USERS_RELATIONSHIP FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE USERS_AUTHORITIES ADD CONSTRAINT AUTHORITY_RELATIONSHIP FOREIGN KEY(AUTHORITY_ID) REFERENCES AUTHORITIES(AUTHORITY_ID);
ALTER TABLE REVIEWS ADD CONSTRAINT REVIEWS_USER_RELATIONSHIP FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID);
ALTER TABLE REVIEWS ADD CONSTRAINT REVIEWS_UNIT_RELATIONSHIP FOREIGN KEY(UNIT_ID) REFERENCES UNITS(UNIT_ID);
