INSERT INTO AUTHORITIES (AUTHORITY_ID, AUTHORITY) VALUES (1,'READ_UNITS');
INSERT INTO AUTHORITIES (AUTHORITY_ID, AUTHORITY) VALUES (2,'WRITE_UNITS');
INSERT INTO AUTHORITIES (AUTHORITY_ID, AUTHORITY) VALUES (3,'READ_REVIEWS');
INSERT INTO AUTHORITIES (AUTHORITY_ID, AUTHORITY) VALUES (4,'WRITE_REVIEWS');
